addReviewers: true
addAssignees: author

reviewers:
  - ruehan
  - shlee9999
  - wonill
  - kimjuyoung99

numberOfReviewers: 2

useReviewGroups: true

reviewGroups:
  optional:
    - ruehan
    - shlee9999
    - wonill
    - kimjuyoung99

skipKeywords:
  - wip

filterUserReviewer: true
